<?php
    //receive php code in string from frontend
    //execute the code
    //return the output generated by the code as a string

    //get the code from the frontend
    $code = $_POST['code'];

    //create a file with the code
    $myfile = fopen("code.php", "w") or die("Unable to open file!");
    fwrite($myfile, "<?php");
    fwrite($myfile, $code);
    fwrite($myfile, "?>");
    fclose($myfile);

    system("C:\wamp\bin\php\php8.1.13\php.exe -f code.php 2>&1", $output);
    //execute the code
    $output = shell_exec('code.php');
    return $output;
    
    //return the output
    // echo $output;
?>